# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87ca123b21afa1eb45618d0130a7050cb518d2c0c7febc53ac14fe19640e4c57ba50cc32877625134e62938fa4d9ccbbe0ab4f4d530d97724026c4d2e6266826

test:
  secret_key_base: b9a3f49a6262c5e112e3d2d4160e52c2c2d7957f0b5643732658fc06cf039213d829f42a604b27e8e998d5c38f53660fb274727328ae6905218e42a5663d7670

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
