---
- name: Create swarm deployment data directory
  file:
    state: directory
    path: "{{ swarm_deployments_path }}/data"
- name: Create service data directory
  file:
    state: directory
    path: "{{ swarm_deployments_path }}/data/{{ item }}"
  loop:
    - postgres
    - mongodb
- name: Create data scripts directory
  file:
    state: directory
    path: "{{ swarm_deployments_path }}/data/scripts"
- name: Copy postgres init script
  template:
    src: init_postgres.sql.j2
    dest: "{{ swarm_deployments_path }}/data/scripts/init_postgres.sql"
- name: Get gdrive
  get_url:
    url: https://github.com/gdrive-org/gdrive/releases/download/2.1.0/gdrive-linux-x64
    dest: /srv/gdrive
    mode: 0755
- name: Copy google service account key to server
  template:
    src: service-account.json
    dest: /srv/service-account.json
- name: Copy backup script to server
  template:
    src: backup_db.sh
    dest: /srv/backup_db.sh
    mode: 0755
- name: Schedule backup with cron
  cron:
    name: backup databases
    hour: 23
    minute: 59
    job: "bash /srv/backup_db.sh"
