---
- name: Create swarm deployment data directory
  file:
    state: directory
    path: "{{ swarm_deployments_path }}/data"
- name: Create service data directory
  file:
    state: directory
    path: "{{ swarm_deployments_path }}/data/{{ item }}"
  loop:
    - postgres
- name: Copy postgres init script
  template:
    src: init_postgres.sql.j2
    dest: "{{ swarm_deployments_path }}/data/scripts/init_postgres.sql"
