---
- name: Basic setup
  hosts:
    - swarm-manager
    - swarm-workers
  roles:
    - common
    - docker
  tasks:
    - hostname: name={{ swarm_node_name }}
    - name: Create swarm deployment data directory
      file:
        state: directory
        path: "{{ swarm_deployments_path }}"
  become_user: root
  become: yes
- name: Initialize Docker Swarm Manager
  hosts: swarm-manager
  tasks:
    - docker_swarm:
        state: present
        advertise_addr: "{{ swarm_manager_ip }}"
      register: swarm_info
  become_user: root
  become: yes
- name: Join workers to te swarm
  hosts: swarm-workers
  tasks:
    - set_fact:
        swarm_facts: "{{ hostvars['swarm-manager-machine']['swarm_info'].swarm_facts }}"
    - docker_swarm:
        state: join
        remote_addrs: [ "{{ swarm_manager_ip }}:2377" ]
        advertise_addr: ""
        join_token: "{{ swarm_facts.JoinTokens.Worker }}"
  become_user: root
  become: yes
- name: Manage Swarm Nodes
  hosts: swarm-manager
  tasks:
    - docker_node:
        hostname: "{{ item.swarm_node_name }}"
        labels:
          gateway: "{{ item.gateway }}"
          data: "{{ item.data }}"
          common: "{{ item.common }}"
      loop: "{{ lookup('items', swarm_labels, wantlist=True) }}"
  become_user: root
  become: yes
- name: Setup Swarm Data Nodes
  hosts: swarm-data-workers
  roles:
    - setup-swarm-data-storage
  become_user: root
  become: yes
