version: '2'

services:
  mongo:
    container_name: data-collector-mongo
    image: 'mongo:3.4'
    environment:
      AUTH: 'no'
    volumes:
      - '/tmp:/data/db/backup'

  data-collector:
    container_name: data-collector 
    depends_on:
      - 'mongo'
    build: .
    ports:
      - 4000:3000
    volumes:
      - '.:/data-collector'
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b 0.0.0.0"
    environment:
      MONGO_USER: 'admin'
      MONGO_PASSWORD: 'admin'
      MONGO_HOST: 'data-collector-mongo'
      MONGO_PORT: 27017
      RABBITMQ_HOST: 'rabbitmq'
      KONG_URI: 'http://kong:8001'
      SELF_HOST: 'data-collector:3000'
      REGISTER_METHOD: 'target'

networks:
  default:
    external:
      name: platform 
