version: '2'

services:
  mongo:
    container_name: data-collector-mongo
    image: 'mongo:3.4'
    environment:
      AUTH: 'no'

  redis:
    image: 'redis'
    container_name: data-collector-redis

  data-collector:
    container_name: data-collector 
    depends_on:
      - 'mongo'
      - 'redis'
    build: .
    ports:
      - 4000:3000
    volumes:
      - '.:/data-collector'
    environment:
      MONGO_USER: 'admin'
      MONGO_PASSWORD: 'admin'
      MONGO_HOST: 'data-collector-mongo'
      MONGO_PORT: 27017
      RABBITMQ_HOST: 'rabbitmq'

  sidekiq:
    container_name: data-collector-sidekiq
    links:
      - 'mongo'
      - 'redis'
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/data-collector'
    environment:
      RAILS_ENV: 'development'
      MONGO_USER: 'admin'
      MONGO_PASSWORD: 'admin'
      MONGO_HOST: 'data-collector-mongo'
      MONGO_PORT: 27017
      RABBITMQ_HOST: 'rabbitmq'

networks:
  default:
    external:
      name: platform 
