version: '2'

services:
  postgres:
    container_name: data-collector-pg
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'

  redis:
    image: 'redis'
    container_name: data-collector-redis

  data-collector:
    container_name: data-collector 
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    ports:
      - 4000:3000
    volumes:
      - '.:/data-collector'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'

  sidekiq:
    container_name: data-collector-sidekiq
    links:
      - 'postgres'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/data-collector'

networks:
  default:
    external:
      name: platform 
