##################################################################
#              Docker Compose file that starts Kong              #
##################################################################

version: '3'

services:
  kong-database:
    image: postgres:9.4
    container_name: kong-database
    ports:
      - 5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes:
      - "db-data-kong-postgres:/var/lib/postgresql/data"
  kong:
    image: kong:latest
    container_name: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    restart: always
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    links:
      - kong-database

  kong-dashboard:
    container_name: kong-dashboard
    image: pgbi/kong-dashboard:v2
    ports:
      - 8080:8080
    environment:
      - KONG_URL=http://kong:8001

  swagger-docs:
    container_name: swagger-docs
    image: swaggerapi/swagger-ui
    ports:
      - 8888:8080
    volumes:
      - './api:/api'
    environment:
      - SWAGGER_JSON=/api/swagger.json

networks:
  default:
    external:
      name: platform 

volumes:
  db-data-kong-postgres:
