version: '2'

services:
  postgres:
    container_name: resource-adaptor-pg
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.6.5
    ports:
      - '15672:15672'
  resource-adaptor:
    container_name: resource-adaptor
    depends_on:
      - 'postgres'
      - 'rabbitmq'
    build: .
    ports:
      - 3002:3000
    volumes:
      - '.:/resource-adaptor'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'

networks:
  default:
    external:
      name: platform 
