# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

gem 'database_cleaner'
gem 'faye'
gem 'jquery-rails'
gem 'kaminari-mongoid'
gem 'mongoid'
gem 'sass-rails', '~> 5.0'
gem 'thin'

# Configure application
gem 'config'

gem 'service-base', path: '../gems/service-base'

group :development, :test do
  gem 'factory_girl_rails', '~> 4.0'
  gem 'faker'
  gem 'rails-controller-testing'
  gem 'rspec-expectations', '~> 3.8.0'
  gem 'rspec-rails', '~> 3.8.0'

  # Call 'byebug' anywhere in the code to stop execution and get a
  # debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'rubocop', '~> 0.74.0', require: false
  gem 'rubocop-rails', require: false
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %>
  # anywhere in the code.
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'web-console', '>= 3.3.0'
  # Spring speeds up development by keeping your application running in the
  # background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'simplecov', require: false, group: :test
