# Be sure to restart your server when you modify this file
#
# Explanation of the required data:
# 1. name: a general name/type of resource
# 2. model: a specific model of the resource
# 3. maker: company responsible to make the resource
# 4. components:
#   * description: shor description of the component that can be used in future full-text search
#   * service_type: name of the module that implements that component's capabilities. This implementation must be placed into lib/component_services.rb file under ComponentServices module
#   * lat: latitude coordinate
#   * lon: longitude coordinate
#   * collec_interval: period of time (in seconds) which the component must wait to perform a new collection. This data can be ignored for event based sensors and actuators
#   * capabilities: set of capabilities that each component answer. Notice that, since a component has a capability "example", it must respond to the method "example"
#
#
# The components is placed as follows:
# 1. USP
# 2. MASP - Av. Paulista
# 3. Zoológico

##
# YAML aliases
#

_parking_sensor: &_parking_sensor
  description: ""
  service_type: "ParkingSpot"
  collect_interval: 10
  capabilities:
    - "spot_availability"

###
# Actual resources definition
#

resources:
  - name: "Arduíno"
    model: "Uno"
    maker: "XPTO"
    components:
      - description: ""
        service_type: "OpenWeatherMap"
        lat: -23.559319
        lon: -46.731476
        collect_interval: 60
        capabilities:
          - "temperature"
          - "pressure"
          - "humidity"
          - "manipulate_led"
      - description: ""
        service_type: "OpenWeatherMap"
        lat: -23.561528
        lon: -46.656009
        collect_interval: 60
        capabilities:
          - "temperature"
          - "pressure"
          - "humidity"
          - "manipulate_led"
      - description: ""
        service_type: "OpenWeatherMap"
        lat: -23.650674
        lon: -46.620484
        collect_interval: 60
        capabilities:
          - "temperature"
          - "pressure"
          - "humidity"
          - "manipulate_led"

  - name: "Parking region 1"
    model: "Generic presence sensor"
    maker: "Generic maker"
    components:
      - <<: *_parking_sensor
        lat: -23.54560817579755
        lon: -46.63851723074913
      - <<: *_parking_sensor
        lat: -23.545443429752037
        lon: -46.63837373256683

  - name: "Parking region 2"
    model: "Generic presence sensor"
    maker: "Generic maker"
    components:
      - <<: *_parking_sensor
        lat: -23.544027097024593
        lon: -46.63990259170532
      - <<: *_parking_sensor
        lat: -23.545443429752037
        lon: -46.63837373256683
