# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 346de7f55bb4630d657493173897701f67740710d48a11761cebe9180b2a7f5b92b7f32ee0cad77593b0f991f20ac2859fc3c4cc087fce13f9578bb2691a4d24

test:
  secret_key_base: 69bb6b877197da0aa893462b77e9fa4f6292c924ae0f074eefe927c2732de108dc89d2afe28c7305548643666eaf332ed057efda597760fe1e4ce6f39b589248

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
