# Be sure to restart your server when you modify this file

# do not include a final slash after the URL
services:
  collector: <%= ENV['DATACOLLECTOR_HOST'] %>
  actuator: <%= ENV['ACTUATORCONTROLLER_HOST'] %>
  rabbitmq: <%= ENV['RABBITMQ_HOST'] %>
