# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

gem 'httparty'
gem 'kong'
gem 'spring', group: :development
gem 'sqlite3'

# Sidekiq and redis
gem 'redis', '~> 4.0'
gem 'redis-namespace'
gem 'sidekiq'

gem 'colorize'

gem 'service-base', path: '../gems/service-base'

group :development, :test do
  gem 'rspec-rails', '~> 3.8.0'
  gem 'rubocop', '~> 0.74.0', require: false
  gem 'rubocop-rails', require: false
end

gem 'simplecov', require: false, group: :test

gem 'sprockets', '~> 3.0'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
