source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.3.8'

gem 'spring', :group => :development
gem 'httparty'

# Sidekiq and redis
gem 'sidekiq'
gem 'redis', '~> 4.0'
gem 'redis-namespace'

gem 'colorize'

gem 'service-base', path: '../gems/service-base'

group :development, :test do
  gem 'rspec-rails'
end

gem 'simplecov', :require => false, :group => :test

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
