source 'https://rubygems.org'

gem 'spring', :group => :development




gem 'httparty'
gem 'rest-client'



# Sidekiq and redis
gem 'sidekiq'
gem 'redis'
gem 'redis-namespace'
gem 'rest-client'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

# RabbitMQ
gem 'bunny', '~> 2.5.1'

gem 'colorize'

gem 'service-base', path: '../gems/service-base'

group :development, :test do
  gem 'rspec-rails'
end

gem 'simplecov', :require => false, :group => :test

gem 'bunny', '~> 2.5.1'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
