---
- name: Install python dependencies
  pip:
    name:
      - jsondiff
      - pyyaml
- name: Create stacks diretory
  file:
    state: directory
    path: "{{ swarm_deployments_path }}/stacks/"
- name: Copy stacks to the manager
  copy:
    src: interscity-platform.yml
    dest: "{{ swarm_deployments_path }}/stacks/"
- docker_stack:
    state: present
    name: interscity-platform
    compose:
      - "{{ swarm_deployments_path }}/stacks/interscity-platform.yml"
