---

- name: Create resource-discoverer service
  docker_container:
    name: resource-discoverer
    image: "{{ resource_discoverer_docker_image }}"
    state: started
    restart: yes
    ports:
    - "{{ resource_discoverer_port }}:{{ resource_discoverer_port }}"
    command: "bundle exec puma -p {{ resource_discoverer_port }} -C config/puma.rb -e production"
    env:
      RAILS_ENV: "{{ rails_env }}"
      RAILS_MAX_THREADS: 200
      SECRET_KEY_BASE: "{{ secret_key_base }}"
      RABBITMQ_HOST: "{{ rabbitmq }}"
      CATALOGUER_HOST: "{{ kong }}:{{ kong_port }}/catalog"
      DATACOLLECTOR_HOST: "{{ kong }}:{{ kong_port }}/collector"
      REGISTER_METHOD: "target"
      KONG_URI: "http://{{ kong }}:{{ kong_admin_port }}"
      SELF_HOST: "{{ self_ip }}:{{ resource_discoverer_port }}"
