require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '**/bin/**/*'
    - '**/db/**/*'
    - '**/config/**/*'
    - '**/script/**/*'
    - '**/features/support/env.rb'
    - '**/vendor/**/*'

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - '**/spec/factories/*.rb'

Metrics/LineLength:
  Max: 120
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
